plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.1'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'org.example'
version = '0.0.1-SNAPSHOT'
description = 'CarServiceProject'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation "com.fasterxml.jackson.dataformat:jackson-dataformat-xml"
    implementation("com.fasterxml.jackson.core:jackson-core:2.20.1")
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    // Тот самый стартер, который дает JdbcTemplate и поддержку DataSource
    implementation 'org.springframework.boot:spring-boot-starter-jdbc'
    // Драйвер для подключения к PostgreSQL
    runtimeOnly 'org.postgresql:postgresql'
    // (Hibernate) Data JPA
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    // Validated for DTO validation
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // Liquidbase
    implementation 'org.springframework.boot:spring-boot-starter-liquibase'
    testImplementation 'org.springframework.boot:spring-boot-starter-liquibase-test'
    //Spring Security
    implementation 'org.springframework.boot:spring-boot-starter-security'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    //JWT
    implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'
    //Spring AOP
    implementation 'org.springframework.boot:spring-boot-starter-aop:3.2.2'
}

tasks.named('test') {
    useJUnitPlatform()
}
