server:
  servlet:
    context-path: /cars-app
spring:
  datasource:
    # Базовые настройки подключения
    url: jdbc:postgresql://localhost:5432/car
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

    # Настройки пула HikariCP (то, что было в твоих config.set...)
    hikari:
      schema: car-service
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000