server:
  servlet:
    context-path: /cars-app
spring:
  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog.yaml
  jpa:
    hibernate:
      ddl-auto:
        none
    show-sql: true
  profiles:
    active:
      local
  application:
    name: local
  datasource:
    # Базовые настройки подключения
    url: jdbc:postgresql://localhost:5432/car
    username: ${USERNAME}
    password: ${PASSWORD}
    driver-class-name: org.postgresql.Driver

    # Настройки пула HikariCP (то, что было в твоих config.set...)
    hikari:
      schema: ${SCHEMA}
      auto-commit: true
      minimum-idle: 2
      idle-timeout: 40000
      maximum-pool-size: 10
      connection-timeout: 10000
      keepalive-time: 30000